name: Deploy Notificion to VPS
 
on:
  push:
    branches: [ "main" ]
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
 
      - name: Copy project to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: "~/SpringTest/docker-notificacion"
 
      - name: Deploy on VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/SpringTest/docker-notificacion
            docker build -t notificacion-app .
            docker network create spring-net || true
            docker stop notificacion-app || true
            docker rm notificacion-app || true
            docker run -d --name notificacion-app \
              --network spring-net \
              --memory="2048m" \
              --cpus="2" \
              -e SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/manager \
              -e SPRING_DATASOURCE_USERNAME=root \
              -e SPRING_DATASOURCE_PASSWORD=cruz123 \
              -p 8091:8091 notificacion-app
